### ISSUE TITLE
Incompatibility with "Serversync Death Tweaks"

### ISSUE THREAD

**Issue by tonyism1** [BruceOfTheBow/ComfyArmorAndQuickSlots#1]
Upon death using Comfy Quickslots and Serversync Deathtweaks, with the option to keep quickslotted items on death, they are lost and not in the grave either.

**Comment by BruceOfTheBow** [comment]
Unfortunately this is not something I will provide support for since I didn't write that mod and that is not an approved mod on the server I play on. I will describe the likely issue though if you would like to fork and do it yourself.

In ComfyQuickSlots' TombstonePatcher, items from the armor and quick slots extra slots (5th row of the inventory) are added to the second grave to prevent having to create a non-vanilla sized tombstone for the regularly generated tombstone. I'm guessing Serversync Death Tweaks hooks into that method as well but since the items have been removed from the inventory already it cannot locate them.
