### ISSUE TITLE
[Feature Requests] Toggle slots layouts, toggle quick slots on/off, toggle unmodded player tombstone compatibility

### ISSUE THREAD

**Issue by Abbanon** [BruceOfTheBow/ComfyArmorAndQuickSlots#2]
This mod is meant to be a direct replacement for [Equipment and Quickslots](https://www.nexusmods.com/valheim/mods/92) as stated on the [Thunderstore page](https://valheim.thunderstore.io/package/ComfyMods/ComfyQuickSlots/), so it would be very nice if it could also include some of the same features. Would you please consider implementing the following in a future update?

- **Toggle armor and quick slot layouts**
Basically, an option to replicate the slot layout of the mod that this one is meant to replace would be amazing.
![Screenshot_1](https://user-images.githubusercontent.com/37251822/204127294-8da6bb79-034f-4edc-9907-49c8542d8cce.png)

- **Toggle quick slots on/off**
Some players, myself included, would like the ability to fully disable the quick slots both visually and functionally, only using the equipment/utility slots. Again, this is an existing option in the mod that this one is meant to replace. It would be very great to have as a feature.

- **Toggle the tombstone compatibility with unmodded players**
This one's a little self-explanatory. Having it as an opt-out feature would allow single tombstones for multiplayer where everyone is using the same mods. It could include a disclaimer to use at your own risk.

**Comment by BruceOfTheBow** [comment]
Hi Abbanon,
I will gladly look into adding  support for 2: a toggle to enable/disable quick slots. Unfortunately I'm not interested in adding support for the EAQS UI in 1. This would be a major effort as comfyquickslots simply extends the vanilla inventory while it would likely need to be refactored to how the inventories are managed in EAQS to support the UI, and frankly that's where some of the bugs came from in the original version. For #3, I will purposefully not add support for this as a vanilla tombstone would certainly lead to item loss on death . I'm not sure what the request is here as the double tombstone is vanilla compatible. Vanilla players see two regular tombstones just as modded players do. Are you trying to run the mod without other players knowing?

**Comment by Abbanon** [comment]
> Are you trying to run the mod without other players knowing?

No actually, I just thought it would be possible to have the space of a single tombstone extended to accommodate the extra slots within the config. For use in situations where *everyone* has the mod. 
Maybe with a disclaimer, saying "if you enable this setting and play with players who do not have this mod, you are at risk of losing your items in the equipment and quick slots."
But if something like that's not possible, and/or outside of the scope for this mod, I fully understand.

Shame about `#1`, but I see why. That's great about `#2` though.

**Comment by BruceOfTheBow** [comment]
Ah I see, unfortunately this will undoubtedly cause someone to enable and get their gear deleted on the server I play on and made this for since we have a mix of modded and unmodded folks. My goal for making this mod was to reduce the number of gear replacement tickets our moderators receive so unfortunately I will not be adding support for that either.

If you'd like to fork and add that behavior in your own version of the mod, it would be a pretty easy add by taking the logic in the TombstonePatch.cs from EAQS and this mod and adding the logic to check a configuration enable.

**Comment by pjmichor** [comment]
I'd like to see the quick slot toggle as well!

Also related to the control of quick slots, is it possible to have new items in the inventory go into a different row instead of being automatically assigned to the quick slots? Or is that how item pick up works that it goes to the leftmost space on the bottom row?

**Comment by BruceOfTheBow** [comment]
Added quickslots on/off toggle to configuration manager in v1.2.0 just released on Thunderstore. Item addition to the inventory uses the vanilla item adding positioning (lower left for most non-equip-able items) which, in this case, are the quick slots.
