### ISSUE TITLE
random items will get stuck in an armor slot.

### ISSUE THREAD

**Issue by drewkeating** [BruceOfTheBow/ComfyArmorAndQuickSlots#7]
Random items will go into the armor slots and I can't get them out. For example, birch seeds are in my utility slot and neck tails are in my cape slot. I got the neck tails out by cooking them - the cooking station removed it automatically. I can also use an armor piece to trade it for the item that is stuck in the armor slot.

**Comment by TechIdeations** [comment]
Currently, if you loot an item with a full inventory, and empty Armor/Utility slots then the items will default to the Helm/Chest/Utility (etc.) and be unmovable until an item is swapped into the respective slot.

**Comment by BruceOfTheBow** [comment]
This is likely a mod conflict. You are likely playing with a mod that patches the same add to inventory methods that CQS does and allows items to be added to those slots. I have not been able to reproduce with just CQS or the allowed mods on our Comfy Valheim server. If you can pinpoint which mod has the conflict I will see if I can work with that mod and mod author for a fix, but I won't be doing the research to figure out what that is out of your mod list.

**Comment by mikkelbrusen** [comment]
Same issue while using the following mods. (picture 1)
Another fun thing about this bug is that even when you equip an item to get the stuck item out, the stuck item cannot be dropped as it has "equipped" status (see the deer trophy in picture 2).
![image](https://user-images.githubusercontent.com/8851482/216320471-37f4dccc-21ac-4579-8aa6-5484c0c4f088.png)
![image](https://user-images.githubusercontent.com/8851482/216320756-7dc02450-8440-42ba-8914-6160e37dec6c.png)

**Comment by BruceOfTheBow** [comment]
> If you can pinpoint which mod has the conflict I will see if I can work with that mod and mod author for a fix, but I won't be doing the research to figure out what that is out of your mod list.

**Comment by nuenuewei** [comment]
Thanks for the mod list, I was having this issue and that allowed me to figure it out.

It's caused by the quiver from BetterArchery.

Disabling the quiver in that mod's config fixes the issue(no need to disable the whole mod.) That mod has other conflicts like this as well.
